### ISSUE TITLE
Mission statement use of "stream"

### ISSUE THREAD

**Issue by LPardue** [w3c/webtransport-charter#12]
The mission statement says:

> The mission of the WebTransport Working Group is to develop APIs that enable data transfer between browsers and servers with support for multiple streams, unidirectional streams, out-of-order delivery, variable reliability and pluggable protocols.

There is overlap of the term "stream", we have QUIC streams and the W3C Streams API, so it is not super clear which is being referred to. And that makes the statement about multiple streams a bit hard to interpret. Is this supposed to mean multiple concurrent streams, multiple sequential streams, multiple connections containing one stream, etc?

Is it necessary to talk about streams in the mission? Would it be as effective to say something like "... concurrent data flows, unidirectional data flows, out-of-order delivery of data across flows, reliable and unreliable data delivery, and pluggable protocols. Then later in the text be more specific about how flows map to QUIC primitives such as streams or DATAGRAMs.

**Comment by jan-ivar** [comment]
You're right that "streams" is an overused term for a lot of different things. But does that mean we avoid it or embrace it where there's consistency?

> W3C Streams API,

If you're referring to the WHATWG [streams](https://streams.spec.whatwg.org/) API, then that's effectively an API abstraction for data flows that the current WICG WebTransport doc fully embraces as its main I/O JS API abstraction. So that seems like a good fit.

If you're referring to W3C's [MediaStream](https://w3c.github.io/mediacapture-main/getusermedia.html#mediastream) API, then that's awkwardly something else that's also quite domain-adjacent (browser's realtime audio/video media abstraction), but not referenced in the WICG WebTransport doc thus far.

Of course, this being a charter and not an API, not presupposing things and going with abstractions may be appropriate.
